# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OSPlatformBrowserVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readable_id', models.CharField(max_length=191, unique=True)),
                ('os_platform', models.CharField(choices=[(b'OS X', b'OS X'), (b'ios', b'iOS'), (b'android', b'Android'), (b'Windows', b'Windows')], max_length=191)),
                ('os_platform_version', models.CharField(max_length=191)),
                ('browser', models.CharField(choices=[(b'safari', b'Safari'), (b'Mobile Safari', b'iOS Mobile Safari'), (b'Android Browser', b'Android Mobile Browser'), (b'edge', b'Microsoft Edge Browser'), (b'ie', b'Microsoft Internet Explorer'), (b'firefox', b'Firefox Browser'), (b'chrome', b'Chrome Browser'), (b'opera', b'Opera Browser')], max_length=191)),
                ('browser_version', models.CharField(blank=True, max_length=191, null=True)),
                ('device', models.CharField(blank=True, choices=[(b'BlackBerry Z30', b'BlackBerry Z30'), (b'BlackBerry PlayBook', b'BlackBerry PlayBook'), (b'Galaxy Note 3', b'Galaxy Note 3'), (b'Galaxy Note II', b'Galaxy Note II'), (b'Galaxy S III', b'Galaxy S III'), (b'Galaxy S5', b'Galaxy S5'), (b'LG Optimus L70', b'LG Optimus L70'), (b'Microsoft Lumia 550', b'Microsoft Lumia 550'), (b'Microsoft Lumia 950', b'Microsoft Lumia 950'), (b'Nokia Lumia 520', b'Nokia Lumia 520'), (b'Nexus 4', b'Nexus 4'), (b'Nexus 5', b'Nexus 5'), (b'Nexus 6', b'Nexus 6'), (b'Nexus 7', b'Nexus 7'), (b'Nexus 10', b'Nexus 10'), (b'Nexus 5X', b'Nexus 5X'), (b'Nexus 6P', b'Nexus 6P'), (b'iPad Mini', b'iPad Mini'), (b'iPad', b'iPad'), (b'iPad Pro', b'iPad Pro'), (b'iPhone 4', b'iPhone 4'), (b'iPhone 5', b'iPhone 5'), (b'iPhone 6', b'iPhone 6'), (b'iPhone 6 Plus', b'iPhone 6 Plus'), (b'Kindle Fire HDX', b'Kindle Fire HDX')], max_length=191, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='osplatformbrowserversion',
            unique_together=set([('os_platform', 'os_platform_version', 'browser', 'browser_version', 'device')]),
        ),
    ]
