# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 10:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.project.apps.automatetest.utils
import src.project.settings.storage_backend


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_uuid', models.UUIDField()),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ScreenshotImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot_uuid', models.UUIDField(unique=True)),
                ('src', models.ImageField(storage=src.project.settings.storage_backend.MediaStorage, upload_to=src.project.apps.automatetest.utils.upload_screenshot)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('build_uuid', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatetest.Project')),
            ],
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('session_uuid', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatetest.TestBuild')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatetest.Project')),
            ],
        ),
        migrations.AddField(
            model_name='screenshotimage',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatetest.TestBuild'),
        ),
        migrations.AddField(
            model_name='screenshotimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatetest.Project'),
        ),
        migrations.AddField(
            model_name='screenshotimage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatetest.TestSession'),
        ),
    ]
