# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatetest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_uuid',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='screenshotimage',
            name='screenshot_uuid',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='testbuild',
            name='build_uuid',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='session_uuid',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
