# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 04:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automatetest', '0002_auto_20171108_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_uuid',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='screenshotimage',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='automatetest.TestBuild'),
        ),
        migrations.AlterField(
            model_name='screenshotimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='automatetest.Project'),
        ),
        migrations.AlterField(
            model_name='screenshotimage',
            name='screenshot_uuid',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='screenshotimage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='automatetest.TestSession'),
        ),
        migrations.AlterField(
            model_name='testbuild',
            name='build_uuid',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='testbuild',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='automatetest.Project'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='automatetest.TestBuild'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='automatetest.Project'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='session_uuid',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
