# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automatetest', '0004_galenreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='galenreport',
            name='build',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='automatetest.TestBuild'),
        ),
        migrations.AddField(
            model_name='galenreport',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='automatetest.Project'),
        ),
        migrations.AddField(
            model_name='galenreport',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='automatetest.TestSession'),
        ),
    ]
