# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import src.project.apps.automatetest.utils
import src.project.settings.storage_backend


class Migration(migrations.Migration):

    dependencies = [
        ('automatetest', '0005_auto_20171110_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('spec_file', models.FileField(storage=src.project.settings.storage_backend.SpecFileStorage, upload_to=src.project.apps.automatetest.utils.handle_upload_spec)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specfiles', to='automatetest.Project')),
            ],
        ),
        migrations.AddField(
            model_name='screenshotimage',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='testbuild',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Success', 'SUCCESS'), ('Failed', 'FAILED')], default='PENDING', max_length=15),
        ),
        migrations.AddField(
            model_name='testsession',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Success', 'SUCCESS'), ('Failed', 'FAILED')], default='PENDING', max_length=15),
        ),
    ]
