# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import src.project.apps.automatetest.utils
import src.project.settings.storage_backend


class Migration(migrations.Migration):

    dependencies = [
        ('automatetest', '0007_auto_20171111_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specfile',
            name='spec_file',
            field=models.FileField(storage=src.project.settings.storage_backend.SpecFileStorage, upload_to=src.project.apps.automatetest.utils.handle_upload_spec),
        ),
    ]
