# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserStackAvailableBrowser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readable_name', models.CharField(blank=True, max_length=255, null=True)),
                ('os_platform', models.CharField(max_length=15)),
                ('os_version', models.CharField(max_length=191)),
                ('browser', models.CharField(max_length=50)),
                ('browser_version', models.CharField(blank=True, max_length=50, null=True)),
                ('device', models.CharField(blank=True, max_length=191, null=True)),
                ('real_mobile', models.NullBooleanField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('os_platform', 'os_version', 'browser'),
                'verbose_name': 'browser',
                'verbose_name_plural': 'browsers',
            },
        ),
    ]
