# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenshot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='browserstackavailablebrowser',
            old_name='real_device',
            new_name='real_mobile',
        ),
    ]
