# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenshot', '0002_auto_20171027_0250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='browserstackavailablebrowser',
            options={'ordering': ('os_platform', 'os_version', 'browser'), 'verbose_name': 'browser', 'verbose_name_plural': 'browsers'},
        ),
        migrations.RenameField(
            model_name='browserstackavailablebrowser',
            old_name='os',
            new_name='os_platform',
        ),
    ]
